@ REM Get absolute path.
@ SETLOCAL ENABLEEXTENSIONS
@ SET ARGS=%*
@ IF NOT DEFINED ARGS @ (
    @ CHDIR
    @ GOTO ENDLOOP_ARGS
)
: LOOP_ARGS
@ SET ARG=%1
@ IF NOT DEFINED ARG @ (
    @ GOTO ENDLOOP_ARGS
)
@ ECHO %~f1
@ SHIFT /1
@ GOTO LOOP_ARGS
: ENDLOOP_ARGS
@ ENDLOCAL
