@ REM Get absolute path.
@ SETLOCAL ENABLEEXTENSIONS
@ SET ERRORLEVEL=
@ SET ARGS=%*
@ IF NOT DEFINED ARGS @ (
    @ CHDIR
    @ GOTO ENDLOOP_ARGS
)
@ SET PT=SET /P ^<NUL
: LOOP_ARGS
@ SET ARG=%1
@ IF NOT DEFINED ARG @ (
    @ GOTO ENDLOOP_ARGS
)
@ %PT%="%~f1" & ECHO=
@ SHIFT /1
@ GOTO LOOP_ARGS
: ENDLOOP_ARGS
@ EXIT /B %ERRORLEVEL%
@ ENDLOCAL
