@ REM Command Prompt startup commands.
@ ECHO "%CMDCMDLINE:"=%" | FIND /I "/C" 1>NUL:
@ IF NOT ERRORLEVEL 1 @ EXIT /B 0

@ REM Set command macros.
@ SET AUTORUN=%~f0
@ DOSKEY ?=ECHO %%ERRORLEVEL%%
@ DOSKEY AUTORUN=CALL "%%AUTORUN%%"
@ DOSKEY BELL=SET /P ^<NUL:^>CON:=
@ DOSKEY CDD=CD /D $*
@ DOSKEY CD~=CD /D %%USERPROFILE%%
@ DOSKEY CHDIRD=CHDIR /D $*
@ DOSKEY CHDIR~=CHDIR /D %%USERPROFILE%%
@ DOSKEY ECHON=SET /P ^<NUL:=$*
@ DOSKEY ERROR=ECHO^>^&2=$*
@ DOSKEY HISTORY=DOSKEY /HISTORY
@ DOSKEY MACROS=DOSKEY /MACROS
@ DOSKEY MACROSOF=DOSKEY /MACROS:$1
@ DOSKEY MKFILE=TYPE NUL:^> $1
@ DOSKEY TEST=IF $* (ECHO>&2=0) ELSE (ECHO>&2=1)

@ REM Set command prompt.
@ IF NOT DEFINED SSH_TTY @ TITLE Command Prompt
@ IF DEFINED SSH_TTY @ TITLE OpenSSH - Command Prompt
@ IF DEFINED SSH_TTY (SET ENTRY=SSH) ELSE (SET ENTRY=CMD)
@ SET PROMPT_TIME=$e[0m$e[31m(*%ENTRY%)$e[0m[$T$H$H$H$H$H$H]
@ SET PROMPT_USER=$e[0m$e[92m%USERNAME%$e[0m@$e[95m%COMPUTERNAME%
@ SET PROMPT_PATH=$e[0m$e[34m$e[1m$P$e[0m$_$e[1m$G$e[0m$S
@ PROMPT %PROMPT_TIME% %PROMPT_USER% %PROMPT_PATH%
@ SET ENTRY=& SET PROMPT_TIME=& SET PROMPT_USER=& SET PROMPT_PATH=
