#!/bin/sh
# Print fields of input by awk.

OPTIONS= && FIELDS= && HELP=
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift 1; break;;
        -h) HELP=info;;
    --help) HELP=info;;
        -*) OPTIONS="$OPTIONS $1";;
         *) FIELDS="$FIELDS \$$1";;
    esac
    shift 1
done

usage ()
{
    CMDNAME=$(basename "$0")
    ARGINFO='[OPTION]... FIELD... [-- FILE...]'
    echo "Usage: $CMDNAME $ARGINFO"
    echo 'Print specific fields of input by awk.'
    echo 'Options are the same as the awk.'
}
[ -n "$HELP" ] && usage && exit 0
[ -z "$FIELDS" ] && usage >&2 && exit 1

awk $OPTIONS -- "{ print $FIELDS }" "$@"
