#!/bin/sh

OPTIONS= && FIELDS= && HELP=
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift 1; break;;
        -h|--help)HELP=yes;;
        -*) OPTIONS="$OPTIONS $1";;
         *) FIELDS="$FIELDS \$$1";;
    esac
    shift 1
done

usage ()
{
    CMDNAME=`basename "$0"`
    ARGNAME='[OPTION]... FIELD... [-- FILE...]'
    echo "Usage: $CMDNAME $ARGNAME"
    echo 'Print specific fields of inputs.'
    echo 'Options are the same as the awk.'
}

[ -n "$HELP" ] && usage && exit 0
[ -z "$FIELDS" ] && usage>&2 && exit 1

awk $OPTIONS "{ print $FIELDS }" "$@"
