#!/bin/sh

SHELL= && HELP=
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift 1; break;;
        -s) shift 1; SHELL="$1";;
        -*) HELP=yes;;
         *) break;;
    esac
    shift 1
done
[ -n "$SHELL" ] || SHELL=/bin/sh

usage ()
{
    CMDNAME=`basename "$0"`
    echo "Usage: $CMDNAME [-s SHELL] FILE..."
    echo 'Create scripts with specific interpreter.'
    echo '    Script content can be read from stdin.'
    echo '    Editor will oepn if no script content.'
    echo 'Options:'
    echo '    -s: interpreter path of new scripts.'
    echo '        default value: /bin/sh'
    echo 'Variables:'
    echo '    EDITOR: script editor path or name.'
}

[ -n "$HELP" ] && usage && exit 0
[ $# -eq 0 ] && usage>&2 && exit 1

CTEMP=/tmp/newscr.$$.tmp
if [ ! -t 0 ]; then
    cat > "$CTEMP"
fi

set -o noclobber
for FILE in "$@"; do
    echo "#!$SHELL" > "$FILE"
    if [ ! -t 0 ]; then
        echo >> "$FILE"
        cat "$CTEMP" >> "$FILE"
    fi
done
chmod +x "$@"

if [ -f "$CTEMP" ]; then
    rm "$CTEMP"
fi

if [ -n "$EDITOR" ] && [ -t 0 ]; then
    "$EDITOR" "$@"
fi
