@ REM Create SSH connection interactively.
@ SETLOCAL ENABLEEXTENSIONS
@ SET ERRORLEVEL=
@ CALL:MAIN %*
@ EXIT /B %ERRORLEVEL%
@ ENDLOCAL

: MAIN
@ CALL:PROMPT %*
@ CALL:DESTINATION
@ IF ERRORLEVEL 1 @ EXIT /B 255
@ ssh %SSH_OPTIONS% %DESTINATION% %SSH_CMDLINE%
@ EXIT /B %ERRORLEVEL%

: PROMPT
@ SET SSH_CMDLINE=%*
@ SET SSH_HOME=%USERPROFILE%\.ssh
@ IF NOT EXIST "%SSH_HOME%" @ MKDIR "%SSH_HOME%"
@ SET KNOWN_DESTS=%SSH_HOME%\known_destinations
@ IF NOT EXIST "%KNOWN_DESTS%" @ TYPE <NUL: "%KNOWN_DESTS%"
@ ECHO Known destinations:& TYPE "%KNOWN_DESTS%"
@ IF DEFINED SSH_OPTIONS @ ECHO SSH options: %SSH_OPTIONS%
@ IF DEFINED SSH_CMDLINE @ ECHO Command line: %SSH_CMDLINE%
@ EXIT /B %ERRORLEVEL%

: DESTINATION
@ SET /P DESTINATION="Destination: "
@ IF NOT DEFINED DESTINATION @ EXIT /B 255
@ FINDSTR /LX /C:"%DESTINATION%" "%KNOWN_DESTS%" 1>NUL:
@ IF ERRORLEVEL 1 @ ECHO:%DESTINATION%>>"%KNOWN_DESTS%"
@ EXIT /B %ERRORLEVEL%
