#!/bin/sh

EXITMSG="exit with code"
test ! -t 1 && FHEAD=">>> %s (%s) <<<\n" ||
    FHEAD="\e[0m>>> \e[35m%s\e[0m \e[36m(%s)\e[0m <<<\n"
test ! -t 2 && FSTAT="!!! $EXITMSG %d !!!\n" ||
    FSTAT="\e[0m!!! \e[33m$EXITMSG\e[0m \e[31m%d\e[0m !!!\n"

PIPE=/tmp/fgit-$$.pipe
test -p $PIPE || mkfifo $PIPE
find . -name .git > $PIPE &

ERRORS=0
while read -r DGIT; do
    REPO=$(dirname "$DGIT" |
           sed 's,^\./,,')
    cd -- "$REPO" || continue
    BRANCH=$(git branch |
             sed -n '/^*/ { s,^* ,,; p }')
    printf "$FHEAD" "$REPO" "$BRANCH"
    git "$@" ; CODE=$?
    if [ $CODE -ne 0 ]; then
        ERRORS=$(($ERRORS + 1))
        printf "$FSTAT" $CODE >&2
    fi
    printf "\n"
    cd -> /dev/null || break
done < $PIPE

test -p $PIPE && rm -f $PIPE
exit $ERRORS
