#!/bin/sh

if file "`readlink -f /proc/$$/fd/1`" |
   grep -q 'character special'; then
    FORMAT="\e[35m%s\e[0m\n"
else
    FORMAT="%s\n"
fi

find . -name .git |
while read DGIT; do
    REPO=`dirname "$DGIT" |
          sed 's=./=='`
    cd "$REPO"
    printf "$FORMAT" "$REPO"
    git "$@"
    printf "\n"
    cd -> /dev/null
done
