#!/bin/sh

OPTS= && FLDS= && HELP=
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift 1; break;;
        -h|--help)HELP=yes;;
        -*) OPTS="$OPTS $1";;
        *)  FLDS="$FLDS \$$1";;
    esac
    shift 1
done

if [ -z "$FLDS" ] || [ -n "$HELP" ]; then
    NAME=`basename "$0"`
    ARGS='[OPTION]... FIELD... [-- FILE...]'
    echo>&2 "Usage: $NAME $ARGS"
    echo>&2 'Print specific fields of inputs.'
    echo>&2 'Options are the same as the awk.'
    exit 255
fi

awk $OPTS "{ print $FLDS }" "$@"
