#!/bin/sh

SEDEXPR= && SEDOPTS= && HELP=
while [ $# -gt 0 ]; do
    case "$1" in
        *:*)SEDEXPR="$SEDEXPR""s:$1:g;";;
        --) shift 1; break;;
        -r) SEDOPTS="$1";;
        -*) HELP=yes;;
        *)  break;;
    esac
    shift 1
done
test -n "$EXPR" || EXPR='s:$:~:g'

if [ $# -eq 0 ] || [ -n "$HELP" ]; then
    CMDNAME=`basename "$0"`
    echo>&2 "Usage: $CMDNAME [-r] [FROM:TO]... FILE..."
    echo>&2 'Duplicate and rename files by FROM:TO exprs.'
    echo>&2 'FROM:TO exprs use regexp; default value: $:~'
    echo>&2 'Options:'
    echo>&2 '    -r: using extended regular expressions.'
fi

for FILE in "$@"; do
    BASEDIR=`dirname "$FILE"`
    DUPNAME=`basename "$FILE" |
         sed $SEDOPTS "$SEDEXPR"`
    cp -r "$FILE" "$BASEDIR/$DUPNAME"
done
