#!/bin/sh
# Duplicate and rename files.

EXPR= && HELP=
while [ $# -gt 0 ]; do
    case "$1" in
       *:*) EXPR="$EXPR""s:$1:g;";;
        --) shift 1; break;;
        -*) HELP=yes;;
         *) break;;
    esac
    shift 1
done
[ -n "$EXPR" ] || EXPR='s:$:~:g'

usage ()
{
    echo "Usage: $(basename "$0") [-r] [FROM:TO]... FILE..."
    echo 'Duplicate and rename files by FROM:TO exprs.'
    echo 'FROM:TO exprs use regexp; default value: $:~'
}
[ "$HELP" = info ] && usage && exit 0
[ "$HELP" = error ] && usage >&2 && exit 1
[ $# -eq 0 ] && usage >&2 && exit 1

for FILE in "$@"; do
    DIR=$(dirname -- "$FILE")
    DUP=$(basename -- "$FILE" |
          sed "$EXPR")
    cp -r -- "$FILE" "$DIR/$DUP"
done
