#!/bin/sh

if [ $# -eq 0 ]; then
    pwd
    exit
fi

if type realpath 1>/dev/null 2>&1; then
    realpath -ms -- "$@"
    exit
fi

for NAME in "$@"; do
    if [ -d "$NAME" -a -x "$NAME" ]; then
        FDIR=`cd -- "$NAME" && pwd`
        echo "$FDIR"
    elif DIR=`dirname -- "$NAME" && pwd` &&
         [ -d "$DIR" -a -x "$DIR" ]; then
        FDIR=`cd -- "$DIR" && pwd`
        FILE=`basename -- "$NAME"`
        test "$FDIR" = / && FDIR=
        echo "$FDIR/$FILE"
    else
        readlink -m -- "$NAME"
    fi
done
